import pre built assets components and styles
obeliskteam/la-95-trucking-show-site pull request #7
Opened 2024-11-06 16:18 UTC by louis17782

## changes made 👍 

#imported:

- styles global.
- components.
- pages.
- images.

closes #2

2024-11-06 18:17 UTC, rpire requested changes
## Cambios Requeridos ♻️

Hola @louis17782, la verdad es que vi todo muy bien, a excepción de la utilización de algunos formatos y algunos errorcitos pequeños. Pero en líneas generales está muy bien. 👍

Recuerda que las imágenes que no son vectores deben estar en formato webp (sé que de momento algunas no son las definitivas, pero hay que tener eso en cuenta). También los vectores deben ir en SVG y casi todos los vectores utilizados son los definitivos.

Ánimo y a seguir trabajando! 👨‍💻

> Nota: decidí dejar las conversaciones de las PR en español para facilitar la revisión y la corrección de errores.

2024-11-06 18:17 UTC, rpire commented on assets/sass/_index.scss
> +@forward 'fronts';
Sería "fonts" en vez de "fronts".

2024-11-06 18:17 UTC, rpire commented on src/components/Footer.astro
Preferiría usar la librería de íconos de [Phosphor](https://phosphoricons.com/) en lugar de font-awesome. Igual entiendo que el footer es algo en lo que vamos a trabajar más adelante.

2024-11-06 18:17 UTC, rpire commented on src/pages/index.astro
> +import "../style/global.scss";
Preferiría que los estilos globales se importaran en Layout, en vez de index y utilizando la sintaxis de `is:global` como en la [documentación de Astro](https://docs.astro.build/en/guides/styling/#global-styles).

2024-11-06 18:17 UTC, rpire commented on assets/sass/_fronts.scss
> +$bevas: 'Bevas', sans-serif;
También se deberían utilizar nombres más generales, como `$text` y `$heading` para esas variables. La razón es que si nos toca cambiar "Bebas Neue" por ejemplo, luego deberíamos cambiar el nombre de la variable en todos los archivos para mantener la consistencia del código.

Cambiemos el nombre ahora que estamos empezando, por el bien de la escalabilidad y el posterior mantenimiento. 👍

2024-11-07 17:52 UTC, rpire approved these changes
## Aprobado! 👍

Lo vi todo muy bien y no vi errores en las librerías y activos que importaste. Buen trabajo.

![GoodNewsGIF](https://github.com/user-attachments/assets/99642ecd-e4d5-4c17-a48d-1fb0de3672cc)

El único comentario que dejo es que hay que quitar los activos que se están importando de Phoshpor de la carpeta `assets` para no repetir las cosas. Pero es algo que se puedo hacer en la siguiente PR.

Puedes fusionar esta rama. 🙌

2024-11-07 17:52 UTC, rpire commented on assets/image/Vector.svg
Si ya estamos importando este ícono de la librería de Phospohor, borrémoslo de assets.

2024-11-07 18:50 UTC, louis17782 commented on assets/image/Vector.svg
Excelente, vamos bien!!

2024-11-07 18:50 UTC, merged